### ISSUE TITLE
小白试图安装DLSiteHelper

### ISSUE THREAD

**Issue by joneszhuang** [xyzkljl1/DLSiteHelperServer#1]
大大你好，我在试图安装你这个helper，但是第二行instruction就看不懂了。"将 openssl/tufao/cpr/mysql 的 dll (在库里) 以及 Qt 的 dll (自行安装) 加入环境路径或拷贝到运行目录" 这里qt的dll是指的哪一个呢？ 然后这个 openssl/tufao/cpr/mysql是在我c盘目录里的吗

**Comment by xyzkljl1** [comment]
openssl/tufao/cpr/mysql可以自行安装，也可以直接用dependencies文件夹下的。
Qt需要自行安装，参考Qt官网，安装后到qt安装目录找到dll文件，需要哪些dll取决于代码使用了哪些qt模块。目前需要的dll有：Qt5Core/Qt5Gui/Qt5Network/Qt5Widgets.dll
